{% set name = "owa-env-desktop" %}
{% set version = "0.4.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/owa_env_desktop-{{ version }}.tar.gz
  sha256: 959dd6f734188379267b3cf860d197708c97b8ee42c638f8f17e283c1d9c9b77

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - owa-core
    - pygetwindow >=0.0.9  # [win]
    - pyobjc-framework-quartz >=10.1  # [osx]
    - pyobjc-framework-applicationservices >=10.1  # [osx]
    - bettercam >=1.0.0  # [win]
    - pynput >=1.8.0
    - opencv >=4.11.0
    - pywin32 >=307
    - __linux  # [linux]
    - __osx    # [osx]
    - __win    # [win]

test:
  imports:
    - owa.env.desktop
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/open-world-agents/open-world-agents
  summary: "Everything you need to build state-of-the-art foundation multimodal desktop agent, end-to-end."
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MilkClouds
